### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by JasonInd** [lakescorp/Ticket-bot-discord#1]
The commands don't seem to work properly.

create_ticket - I need to type this out twice for it to properly create the message and have the reaction added underneath.
The first time I do this command it creates a ticket channel automatically and removes emoji to react to - shouldn't do this right should just make the message with the emoji to react to then open the ticket channel.

addmentionrole -  Doesn't add any role properly - as in you can type out the correct input and it says the role is added but when you create a new ticket it doesn't appear to mention the role.
delmentionrole - Not sure if it properly removes because it doesn't add any support role correctly but you can get it give you successfully removed message

**Comment by lagosproject** [comment]
Ok, in these days I will take a look and try to fix it, thanks for notifying.

**Comment by JasonInd** [comment]
Thank you for responding, I would like to add a suggestion for an enhancement is that possibly after the ticket is closed to create a text file of the ticket chat log and send to admin and person who opened ticket

**Comment by lagosproject** [comment]
I liked the idea, I will put it as a function for future versions. I hope that this weekend I will have time to do it.

**Comment by lagosproject** [comment]
The problem with create_ticket you are talking about does not occur to me. In the meantime the problem with the mentions has been solved.

**Comment by JasonInd** [comment]
Hey thanks for fixing the mention problem, for the create_ticket one I'm not too sure on the consistency of the bug sometimes it works first time sometimes it doesn't, the main thing is that is works eventually if you type create_ticket enough times so that it doesn't remove the reaction. I guess just the .txt file now.

From this repository of another ticket system I found some code that might help with creating the .txt file: https://github.com/Skelmis/DPY-Ticket-Bot/blob/master/utils/util.py

```async def CloseTicket(bot, channel, author, reason=None):
    if not IsATicket(channel.id):
        await channel.send("I cannot close this as it is not a ticket.")
        return

    reason = reason or "No closing reason specified."
    ticketId = GetTicketId(channel.id)
    messages = await channel.history(limit=None, oldest_first=True).flatten()
    ticketContent = " ".join(
        [f"{message.content} | {message.author.name}\n" for message in messages]
    )
    with open(f"tickets/{ticketId}.txt", "w", encoding="utf8") as f:
        f.write(f"Here is the message log for ticket ID {ticketId}\n----------\n\n")
        f.write(ticketContent)

    fileObject = discord.File(f"tickets/{ticketId}.txt")
    logChannel = bot.get_channel(bot.log_channel_id)
    await SendLog(
        bot,
        author,
        logChannel,
        f"Closed Ticked: Id {ticketId}",
        f"Close Reason: {reason}",
        0xF42069,
        file=fileObject,
    )
    await channel.delete()


async def SendLog(
    bot: commands.Bot,
    author,
    channel,
    contentOne: str = "Default Message",
    contentTwo: str = "\uFEFF",
    color=0x808080,
    timestamp=None,
    file: discord.File = None,
):
    embed = discord.Embed(title=contentOne, description=contentTwo, color=color)

    if timestamp:
        embed.timestamp = timestamp

    embed.set_author(name=author.name, icon_url=author.avatar_url)
    await channel.send(embed=embed)

    if file:
        await channel.send(file=file)```

**Comment by lagosproject** [comment]
All the mention roles problem have been solved, i suggest you to delete the fields of roles in the data.json file
