### ISSUE TITLE
Privileges

### ISSUE THREAD

**Issue by Navoichyk** [lakescorp/Ticket-bot-discord#4]
I just tried to run your discord bot but its telling me it is asking for privileges that the bot does not have. The bot has admin privileges so I'm not sure what to do with this.

**Comment by mdm9300404** [comment]
Go to the [Developer Portal](https://discord.com/developers/applications), and click the application you created. On the left side, underneath where it says "OAuth2", click "Bot". Scroll down and find "Privileged Gateway Intents", then enable all three options (Presence Intent, Server Members Intent, and Message Content Intent)

**Comment by lagosproject** [comment]
I understand It's solved so I will close the issue
